### ISSUE TITLE
BLS report: transit time (t0) reported seems to be incorrect

### ISSUE THREAD

**Issue by orionlee** [noraeisner/LATTE#22]
E.g., excerpt of the report for TIC 149601126 (with sector 27+28 data). The `t0` reported (both in the graph and the table) is `12.69`, but the actual transit time, as seen in the dips in the graph, is ~ BTJD 2056, or day 19.8

![image](https://user-images.githubusercontent.com/250644/97094494-f4a67b00-1609-11eb-8233-d5327a4d0d3a.png)

The full report: https://drive.google.com/open?id=1HoJJyX6pAOdNFgtBU7PgwoKO6hHLBIiJ

**Comment by noraeisner** [comment]
Hi, thanks for spotting this bug. I've fixed it in the LATTE-dev version  :). 
![55525572_bls_first](https://user-images.githubusercontent.com/43934902/97189804-47686a00-17a5-11eb-9fde-f3f3a914bca1.png)
