### ISSUE TITLE
Minor report enhancement: include the time window in per-pixel plots

### ISSUE THREAD

**Issue by orionlee** [noraeisner/LATTE#24]
The per-pixel plots are quite useful. It'd be even better if it also indicates the time window of the displayed lightcurve segment, e.g, indicate the begin / end BTJD.

**Comment by noraeisner** [comment]
Great idea, thanks. I've added a figure title with the marked transit time and the range that is shown (in the LATTE-dev branch only or now). I'm going to close this issue but let me know if this isn't what you had in mind.
