### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by Pietertju** [noraeisner/LATTE#46]
I have problems when trying to run LATTE, I made sure I have all dependencies on the correct version (mainly matplotlip 3.2.0 and astropy 4.0). I am using python 3.8, the command output when I run the python -m LATTE command is shown below, does someone know how to fix this?
![latteproblem](https://user-images.githubusercontent.com/14914079/148122852-e775fec4-aacc-4eed-8c87-03bedfa84338.png)

**Comment by Night-Vega** [comment]
Even I face this problem. I believe it is due to the operating systems. Nora uses iMac and the codes work there, so maybe it won't work for Windows.

**Comment by Pietertju** [comment]
I got it to work on windows with Python 3.8.10, astropy 4.3.1, matplotlib 3.2.0 and numpy 1.17.4

**Comment by Night-Vega** [comment]
I'll need to try it as well!

**Comment by AJAX6255** [comment]
Personally, I was never able to get it to work on windows (even after more
than a week of trying). When I installed it on a Linux machine it ran
perfectly.
